[versions]
maven-group = "band.kessokuteatime"
archives-name = "nightautoconfig"
mod = "1.0.6"
loader = "forge"

minecraft = "1.20.1"
yarn = "1.20.1+build.10"
forge = "1.20.1-47.3.5"
architectury-loom = "1.6-SNAPSHOT"
modpublisher = "2.1.0"
shadow = "8.+"

cloth-config = "11.1.118"
night-config = "3.8.0"

# id
id-modrinth = "HQpcCFZg"
id-curseforge = "1061154"

# display
display-name = "Night Auto Config"
display-loader = "Forge"
display-version = "1.20.1"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }
forge = { group = "net.minecraftforge", name = "forge", version.ref = "forge" }

cloth-config = { group = "me.shedaniel.cloth", name = "cloth-config-forge", version.ref = "cloth-config" }

night-config-core = { group = "com.electronwill.night-config", name = "core", version.ref = "night-config" }
night-config-json = { group = "com.electronwill.night-config", name = "json", version.ref = "night-config" }
night-config-toml = { group = "com.electronwill.night-config", name = "toml", version.ref = "night-config" }
night-config-hocon = { group = "com.electronwill.night-config", name = "hocon", version.ref = "night-config" }
night-config-yaml = { group = "com.electronwill.night-config", name = "yaml", version.ref = "night-config" }

[plugins]
architectury-loom = { id = "dev.architectury.loom", version.ref = "architectury-loom" }
modpublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modpublisher" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }

[bundles]
night-config = ["night-config-core", "night-config-json", "night-config-toml", "night-config-hocon", "night-config-yaml"]
